allowBuilds:
  esbuild: set this to true or false
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@typescript-eslint/eslint-plugin@8.71.0'
  - '@typescript-eslint/type-utils@8.71.0'
